load ../common/parameters
load ../../common/parameters

mod PARAMETERS is
  inc PARAMETERS-COMMON + PARAMETERS-BASE-COMMON .

  --- Resolver timeouts
  op rsvTimeout? : -> Bool .
  eq rsvTimeout? = true [owise] .

  op rsvTimeout : -> Float .
  eq rsvTimeout = 0.8 [owise] .

  op rsvOverallTimeout? : -> Bool .
  eq rsvOverallTimeout? = false [owise] .

  op rsvOverallTimeout : -> Float .
  eq rsvOverallTimeout = 10.0 [owise] .

  op dropMsgsForNXActors? : -> Bool . --- whether messages addressed to non-existent actors should be dropped silently
  eq dropMsgsForNXActors? = false [owise] .

  --- Name server resource bounds:

  --- Enable resource bounds (see below)
  op nsResourceBounds? : -> Bool .
  eq nsResourceBounds? = false [owise] .

  op nsReqProcDelay : -> Float . --- request processing delay
  eq nsReqProcDelay = sampleExp(1.0) [owise] . --- sampleExp(k) --> on average, k requests are processed per time unit

  op nsQueueSize : -> Nat . --- size of request queue; if queue is full, incoming requests are dropped
  eq nsQueueSize = 10 [owise] .

  --- Attacker configuration
  op atkrInitDelay : -> Float .
  eq atkrInitDelay = sampleExp(1.0) . --- delay for attacker client start signal

endm
eof

************  TESTING
ops aX aY : -> Address .
op noContent : -> Content .
op mXY : -> Msg .
eq mXY = to aX from aY : noContent .

